// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqtTozWkSXohZ9VG_uYtDIgjS-J1RRRVg',
    appId: '1:519582688312:web:a285dafd7bbce64d0332cd',
    messagingSenderId: '519582688312',
    projectId: 'social-app-2089e',
    authDomain: 'social-app-2089e.firebaseapp.com',
    storageBucket: 'social-app-2089e.appspot.com',
    measurementId: 'G-9XJ3KP4G2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcLz-tpl-SauTJkBB7e7_rNNrOWIaS7E',
    appId: '1:519582688312:android:fe23c29ce33e47000332cd',
    messagingSenderId: '519582688312',
    projectId: 'social-app-2089e',
    storageBucket: 'social-app-2089e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVb0BVWsYGNhbwnM8uj8KwZVWLUoK-CSQ',
    appId: '1:519582688312:ios:2762de5d7bb9d7910332cd',
    messagingSenderId: '519582688312',
    projectId: 'social-app-2089e',
    storageBucket: 'social-app-2089e.appspot.com',
    iosClientId: '519582688312-f096ase1j7uob55ssm6r3gnsaj1jqoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVb0BVWsYGNhbwnM8uj8KwZVWLUoK-CSQ',
    appId: '1:519582688312:ios:2762de5d7bb9d7910332cd',
    messagingSenderId: '519582688312',
    projectId: 'social-app-2089e',
    storageBucket: 'social-app-2089e.appspot.com',
    iosClientId: '519582688312-f096ase1j7uob55ssm6r3gnsaj1jqoj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
